/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldCup2026RouteImport } from './routes/world-cup-2026'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SetsRouteImport } from './routes/sets'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PostersRouteImport } from './routes/posters'
import { Route as PolosRouteImport } from './routes/polos'
import { Route as PlayerVersionRouteImport } from './routes/player-version'
import { Route as JerseyAdminRouteImport } from './routes/jersey-admin'
import { Route as JacketsRouteImport } from './routes/jackets'
import { Route as FanVersionRouteImport } from './routes/fan-version'
import { Route as EmbroideryRouteImport } from './routes/embroidery'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as ApiPublicInvoiceIdRouteImport } from './routes/api/public/invoice.$id'
import { Route as AuthenticatedAccountOrdersIdRouteImport } from './routes/_authenticated/account.orders.$id'

const WorldCup2026Route = WorldCup2026RouteImport.update({
  id: '/world-cup-2026',
  path: '/world-cup-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsRoute = SetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PostersRoute = PostersRouteImport.update({
  id: '/posters',
  path: '/posters',
  getParentRoute: () => rootRouteImport,
} as any)
const PolosRoute = PolosRouteImport.update({
  id: '/polos',
  path: '/polos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerVersionRoute = PlayerVersionRouteImport.update({
  id: '/player-version',
  path: '/player-version',
  getParentRoute: () => rootRouteImport,
} as any)
const JerseyAdminRoute = JerseyAdminRouteImport.update({
  id: '/jersey-admin',
  path: '/jersey-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const JacketsRoute = JacketsRouteImport.update({
  id: '/jackets',
  path: '/jackets',
  getParentRoute: () => rootRouteImport,
} as any)
const FanVersionRoute = FanVersionRouteImport.update({
  id: '/fan-version',
  path: '/fan-version',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbroideryRoute = EmbroideryRouteImport.update({
  id: '/embroidery',
  path: '/embroidery',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const ApiPublicInvoiceIdRoute = ApiPublicInvoiceIdRouteImport.update({
  id: '/api/public/invoice/$id',
  path: '/api/public/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountOrdersIdRoute =
  AuthenticatedAccountOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAccountOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/embroidery': typeof EmbroideryRoute
  '/fan-version': typeof FanVersionRoute
  '/jackets': typeof JacketsRoute
  '/jersey-admin': typeof JerseyAdminRoute
  '/player-version': typeof PlayerVersionRoute
  '/polos': typeof PolosRoute
  '/posters': typeof PostersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sets': typeof SetsRoute
  '/shop': typeof ShopRoute
  '/shorts': typeof ShortsRoute
  '/wishlist': typeof WishlistRoute
  '/world-cup-2026': typeof WorldCup2026Route
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRouteWithChildren
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/account/orders/$id': typeof AuthenticatedAccountOrdersIdRoute
  '/api/public/invoice/$id': typeof ApiPublicInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/embroidery': typeof EmbroideryRoute
  '/fan-version': typeof FanVersionRoute
  '/jackets': typeof JacketsRoute
  '/jersey-admin': typeof JerseyAdminRoute
  '/player-version': typeof PlayerVersionRoute
  '/polos': typeof PolosRoute
  '/posters': typeof PostersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sets': typeof SetsRoute
  '/shop': typeof ShopRoute
  '/shorts': typeof ShortsRoute
  '/wishlist': typeof WishlistRoute
  '/world-cup-2026': typeof WorldCup2026Route
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRouteWithChildren
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/account/orders/$id': typeof AuthenticatedAccountOrdersIdRoute
  '/api/public/invoice/$id': typeof ApiPublicInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/embroidery': typeof EmbroideryRoute
  '/fan-version': typeof FanVersionRoute
  '/jackets': typeof JacketsRoute
  '/jersey-admin': typeof JerseyAdminRoute
  '/player-version': typeof PlayerVersionRoute
  '/polos': typeof PolosRoute
  '/posters': typeof PostersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sets': typeof SetsRoute
  '/shop': typeof ShopRoute
  '/shorts': typeof ShortsRoute
  '/wishlist': typeof WishlistRoute
  '/world-cup-2026': typeof WorldCup2026Route
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRouteWithChildren
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/account/orders/$id': typeof AuthenticatedAccountOrdersIdRoute
  '/api/public/invoice/$id': typeof ApiPublicInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/embroidery'
    | '/fan-version'
    | '/jackets'
    | '/jersey-admin'
    | '/player-version'
    | '/polos'
    | '/posters'
    | '/reset-password'
    | '/sets'
    | '/shop'
    | '/shorts'
    | '/wishlist'
    | '/world-cup-2026'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/category/$slug'
    | '/product/$slug'
    | '/account/orders'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/'
    | '/account/orders/$id'
    | '/api/public/invoice/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/embroidery'
    | '/fan-version'
    | '/jackets'
    | '/jersey-admin'
    | '/player-version'
    | '/polos'
    | '/posters'
    | '/reset-password'
    | '/sets'
    | '/shop'
    | '/shorts'
    | '/wishlist'
    | '/world-cup-2026'
    | '/account'
    | '/checkout'
    | '/category/$slug'
    | '/product/$slug'
    | '/account/orders'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/products'
    | '/admin'
    | '/account/orders/$id'
    | '/api/public/invoice/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/embroidery'
    | '/fan-version'
    | '/jackets'
    | '/jersey-admin'
    | '/player-version'
    | '/polos'
    | '/posters'
    | '/reset-password'
    | '/sets'
    | '/shop'
    | '/shorts'
    | '/wishlist'
    | '/world-cup-2026'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/checkout'
    | '/category/$slug'
    | '/product/$slug'
    | '/_authenticated/account/orders'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/'
    | '/_authenticated/account/orders/$id'
    | '/api/public/invoice/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  EmbroideryRoute: typeof EmbroideryRoute
  FanVersionRoute: typeof FanVersionRoute
  JacketsRoute: typeof JacketsRoute
  JerseyAdminRoute: typeof JerseyAdminRoute
  PlayerVersionRoute: typeof PlayerVersionRoute
  PolosRoute: typeof PolosRoute
  PostersRoute: typeof PostersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetsRoute: typeof SetsRoute
  ShopRoute: typeof ShopRoute
  ShortsRoute: typeof ShortsRoute
  WishlistRoute: typeof WishlistRoute
  WorldCup2026Route: typeof WorldCup2026Route
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicInvoiceIdRoute: typeof ApiPublicInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world-cup-2026': {
      id: '/world-cup-2026'
      path: '/world-cup-2026'
      fullPath: '/world-cup-2026'
      preLoaderRoute: typeof WorldCup2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets': {
      id: '/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof SetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posters': {
      id: '/posters'
      path: '/posters'
      fullPath: '/posters'
      preLoaderRoute: typeof PostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polos': {
      id: '/polos'
      path: '/polos'
      fullPath: '/polos'
      preLoaderRoute: typeof PolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-version': {
      id: '/player-version'
      path: '/player-version'
      fullPath: '/player-version'
      preLoaderRoute: typeof PlayerVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jersey-admin': {
      id: '/jersey-admin'
      path: '/jersey-admin'
      fullPath: '/jersey-admin'
      preLoaderRoute: typeof JerseyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jackets': {
      id: '/jackets'
      path: '/jackets'
      fullPath: '/jackets'
      preLoaderRoute: typeof JacketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan-version': {
      id: '/fan-version'
      path: '/fan-version'
      fullPath: '/fan-version'
      preLoaderRoute: typeof FanVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embroidery': {
      id: '/embroidery'
      path: '/embroidery'
      fullPath: '/embroidery'
      preLoaderRoute: typeof EmbroideryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/api/public/invoice/$id': {
      id: '/api/public/invoice/$id'
      path: '/api/public/invoice/$id'
      fullPath: '/api/public/invoice/$id'
      preLoaderRoute: typeof ApiPublicInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/orders/$id': {
      id: '/_authenticated/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AuthenticatedAccountOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAccountOrdersRoute
    }
  }
}

interface AuthenticatedAccountOrdersRouteChildren {
  AuthenticatedAccountOrdersIdRoute: typeof AuthenticatedAccountOrdersIdRoute
}

const AuthenticatedAccountOrdersRouteChildren: AuthenticatedAccountOrdersRouteChildren =
  {
    AuthenticatedAccountOrdersIdRoute: AuthenticatedAccountOrdersIdRoute,
  }

const AuthenticatedAccountOrdersRouteWithChildren =
  AuthenticatedAccountOrdersRoute._addFileChildren(
    AuthenticatedAccountOrdersRouteChildren,
  )

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRouteWithChildren
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRouteWithChildren,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  EmbroideryRoute: EmbroideryRoute,
  FanVersionRoute: FanVersionRoute,
  JacketsRoute: JacketsRoute,
  JerseyAdminRoute: JerseyAdminRoute,
  PlayerVersionRoute: PlayerVersionRoute,
  PolosRoute: PolosRoute,
  PostersRoute: PostersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetsRoute: SetsRoute,
  ShopRoute: ShopRoute,
  ShortsRoute: ShortsRoute,
  WishlistRoute: WishlistRoute,
  WorldCup2026Route: WorldCup2026Route,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicInvoiceIdRoute: ApiPublicInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
